// <auto-generated />
namespace BooksDownloadingPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seatnumberaddedtoregister : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seatnumberaddedtoregister));
        
        string IMigrationMetadata.Id
        {
            get { return "201902151401084_seatnumberaddedtoregister"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
